const GOOGLE_CLIENT_ID="GANTI_DENGAN_GOOGLE_CLIENT_ID_KAMU.apps.googleusercontent.com";
const FK="rojak_drive_files",UK="rojak_drive_user";let files=[],user=null,editId=null;
document.addEventListener("DOMContentLoaded",()=>{load();bind();initGoogle();renderAll()});
function load(){try{files=JSON.parse(localStorage.getItem(FK)||"[]")}catch{files=[]}try{user=JSON.parse(localStorage.getItem(UK)||"null")}catch{user=null}user?showApp():showLogin()}
function save(){localStorage.setItem(FK,JSON.stringify(files));storage()}
function showLogin(){document.getElementById("loginScreen").classList.remove("hidden");document.getElementById("app").classList.add("hidden")}
function showApp(){document.getElementById("loginScreen").classList.add("hidden");document.getElementById("app").classList.remove("hidden");profile()}
function initGoogle(){const b=document.getElementById("googleButton");if(typeof google==="undefined"){document.getElementById("loginStatus").textContent="Google Login belum termuat.";return}if(GOOGLE_CLIENT_ID.includes("GANTI_DENGAN")){document.getElementById("loginStatus").textContent="Isi Client ID di script.js.";return}google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:login});google.accounts.id.renderButton(b,{theme:"filled_black",size:"large",shape:"pill",width:300})}
function login(r){try{const p=jwt(r.credential);user={id:p.sub,name:p.name||"User",email:p.email||"",picture:p.picture||""};localStorage.setItem(UK,JSON.stringify(user));showApp();toast("Login berhasil")}catch{document.getElementById("loginStatus").textContent="Login Google gagal."}}
function jwt(t){const x=t.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");return JSON.parse(decodeURIComponent(atob(x).split("").map(c=>"%"+("00"+c.charCodeAt(0).toString(16)).slice(-2)).join("")))}
function bind(){document.querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>page(x.dataset.page));document.querySelectorAll("[data-action]").forEach(x=>x.onclick=()=>act(x.dataset.action));document.getElementById("newTxtButton").onclick=()=>openTxt();document.getElementById("folderButton").onclick=folder;document.getElementById("uploadButton").onclick=()=>fileInput.click();document.getElementById("fileInput").onchange=upload;document.getElementById("demoLogin").onclick=()=>{user={id:"demo",name:"Rojak User",email:"demo@rojak.local"};localStorage.setItem(UK,JSON.stringify(user));showApp();toast("Mode demo aktif")};document.getElementById("logoutButton").onclick=()=>{user=null;localStorage.removeItem(UK);showLogin()};document.getElementById("searchInput").oninput=e=>renderFiles(files.filter(f=>f.name.toLowerCase().includes(e.target.value.toLowerCase())));document.getElementById("saveTxt").onclick=saveTxt;document.getElementById("cancelTxt").onclick=closeTxt;document.getElementById("closeTxt").onclick=closeTxt;document.getElementById("aiSendButton").onclick=sendAI;document.getElementById("aiInput").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendAI()}};document.getElementById("clearChat").onclick=()=>document.getElementById("aiChat").innerHTML='<div class="msg bot">Chat dibersihkan.</div>'}
function act(a){if(a==="txt")openTxt();if(a==="folder")folder();if(a==="upload")fileInput.click();if(a==="ai")page("ai")}
function page(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById("page-"+p).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(p==="recent")recent();if(p==="starred")starred()}
function openTxt(id){editId=id||null;const f=id&&files.find(x=>x.id===id);document.getElementById("txtTitle").textContent=f?"Edit File TXT":"Buat File TXT";document.getElementById("txtName").value=f?f.name:"catatan.txt";document.getElementById("txtContent").value=f?.content||"";document.getElementById("txtModal").classList.remove("hidden");setTimeout(()=>txtName.focus(),50)}
function closeTxt(){editId=null;document.getElementById("txtModal").classList.add("hidden")}
function saveTxt(){let n=txtName.value.trim()||"catatan.txt";if(!n.toLowerCase().endsWith(".txt"))n+=".txt";const c=txtContent.value;if(editId){const f=files.find(x=>x.id===editId);Object.assign(f,{name:n,content:c,size:new Blob([c]).size,updatedAt:Date.now()})}else files.push({id:uid(),name:n,type:"txt",content:c,size:new Blob([c]).size,starred:false,createdAt:Date.now()});save();closeTxt();renderAll();toast("TXT tersimpan")}
function folder(){const n=prompt("Nama folder:");if(!n?.trim())return;files.push({id:uid(),name:n.trim(),type:"folder",size:0,starred:false,createdAt:Date.now()});save();renderAll();toast("Folder dibuat")}
function upload(e){const a=[...e.target.files];a.forEach(f=>{if(f.type.startsWith("image/")){const r=new FileReader();r.onload=()=>{files.push({id:uid(),name:f.name,type:"image",preview:r.result,size:f.size,starred:false,createdAt:Date.now()});save();renderAll()};r.readAsDataURL(f)}else files.push({id:uid(),name:f.name,type:"file",size:f.size,starred:false,createdAt:Date.now()})});save();renderAll();e.target.value="";toast(a.length+" file ditambahkan")}
function renderAll(){renderFiles(files);recent();starred();profile();storage()}
function renderFiles(list){const g=document.getElementById("fileGrid");g.innerHTML="";document.getElementById("emptyState").style.display=list.length?"none":"block";cards(g,list)}
function recent(){cards(document.getElementById("recentGrid"),[...files].sort((a,b)=>b.createdAt-a.createdAt))}
function starred(){cards(document.getElementById("starredGrid"),files.filter(x=>x.starred))}
function cards(g,list){g.innerHTML="";if(!list.length){g.innerHTML='<div class="empty">Belum ada file.</div>';return}list.forEach(f=>{const d=document.createElement("div");d.className="card";let p=f.type==="image"&&f.preview?`<img src="${f.preview}">`:f.type==="folder"?"📁":f.type==="txt"?"📝":"📄";d.innerHTML=`<button class="star ${f.starred?"active":""}">★</button><div class="preview">${p}</div><div class="name">${esc(f.name)}</div><div class="meta">${sz(f.size)}</div>`;d.querySelector(".star").onclick=e=>{e.stopPropagation();f.starred=!f.starred;save();renderAll()};d.onclick=()=>f.type==="txt"?openTxt(f.id):toast(f.type==="folder"?"Folder dipilih":f.name);g.appendChild(d)})}
function profile(){if(!user)return;document.getElementById("profileName").textContent=user.name;document.getElementById("settingsName").textContent=user.name;document.getElementById("settingsEmail").textContent=user.email}
function storage(){document.getElementById("storageText").textContent=files.length+" item";document.getElementById("storageBar").style.width=Math.min(100,files.length*4)+"%"}
async function sendAI(){const i=document.getElementById("aiInput"),b=document.getElementById("aiSendButton"),q=i.value.trim();if(!q)return;msg(q,"user");i.value="";b.disabled=true;aiStatus.textContent="Berpikir...";try{msg(await askAI(q),"bot")}catch(e){msg("Maaf, Rojak AI sedang mengalami masalah.\n\n"+e.message,"error")}b.disabled=false;aiStatus.textContent="Online"}
function msg(t,c){const d=document.createElement("div");d.className="msg "+c;d.textContent=t;aiChat.appendChild(d);aiChat.scrollTop=aiChat.scrollHeight}
async function askAI(prompt){const r=await fetch("/api/gemini",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt})});const raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw Error("Endpoint /api/gemini tidak ditemukan. HTTP "+r.status)}if(!r.ok)throw Error(d.error||"Gemini gagal");return d.text||"Jawaban kosong"}
function uid(){return Date.now()+"_"+Math.random().toString(36).slice(2)}function sz(n){if(!n)return"0 KB";const u=["B","KB","MB","GB"],i=Math.min(3,Math.floor(Math.log(n)/Math.log(1024)));return(n/1024**i).toFixed(i?1:0)+" "+u[i]}function esc(s){const d=document.createElement("div");d.textContent=s;return d.innerHTML}function toast(s){const t=document.getElementById("toast");t.textContent=s;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),2200)}
